### ISSUE TITLE
Problem with creating Clue Report

### ISSUE THREAD

**Issue by RonRN18** [ncssar/radiolog#347] opened 2017-09-14 21:00 UTC
I found that printing clues caused Python to crash. Before investigating why it was crashing, I initially changed line 207 of _clueDialog_ui.py_ from:
`self.clueReportPrintCheckBox.setChecked(True)`
to
`self.clueReportPrintCheckBox.setChecked(False)`

By doing this, it did not automatically print the clue upon creation. This at least allowed me to enter clues without crashing because I forgot to uncheck the print button.

I then looked at the error created when trying to print the clue report and found you had created a solution but I did not see any documentation about making the fix. The problem appears to revolve around the Python module fdfgen and the order of a couple lines. I now have it working properly when I run the following line as a Windows administrator from the Python install directory:

`pip install -e git+https://github.com/caver456/fdfgen.git#egg=fdfgen`

This command will download and install Caver456's fork of fdfgen.

**Comment by caver456** [comment] 2017-09-14 22:27
Interesting, thanks for pointing this out.  Sounds like the fdfgen project
may not have processed the pull request?  Regardless, radiolog should
handle the error gracefully.  I am on the road at the moment, will address
this next week.

**Comment by caver456** [comment] 2017-09-30 18:04
Looked at this a bit more - the fdfgen project author did merge this fix on May 9 2017; is it possible you had fdfgen from earlier than that?  My fork hasn't been changed since May 9 but the master repo has; maybe some error got introduced between then and now, so, I will give it a shot with the latest fdfgen and see if I get an error.

**Comment by caver456** [comment] 2017-09-30 18:38
I have fdfgen 0.16.0 (from 'pip list').   That's the latest available via pip (Feb 2017 according to the changelog), so it looks like it hasn't been propagated to pip in a while (I am not familiar with the inner workings of how their merges get propagated to pip's bucket o' code).  Also verified that my fork is still 100% identical with what you get from 'clone or download' on the upstream repo (ccnmtl/fdfgen).

A clean print (submitting the clue dialog while the print checkbox is checked) looks like this:

5215:7: finished newEntryPost
5219:vText:
5219:resetting last mod age for Team 1
5219:generating clue report pdf: C:\Users\caver\Documents\New_Incident_2017_09_30_111332_clue01.pdf
5219:Calling pdftk with the following command:
5219:pdftk "clueReportFillable.pdf" fill_form "C:\Users\caver\Documents\New_Incident_2017_09_30_111332_clue01.fdf" output "C:\Users\caver\Documents\New_Incident_2017_09_30_111332_clue01.pdf" flatten
5219:accepted - calling close

Maybe these questions are moot if you already grabbed the version from my fork, but if not:

Did you install it originally using pip, or something else?  As the acid test, can you look in the actual code at fdfgen/__init__.py and see if you have the comment "make sure value is str right away..." at line 52?  Do you have any more detail, like the transcript, from the print errors?

**Comment by caver456** [comment] 2017-11-23 19:43
Talked with the fdfgen author last week, since another user had the same issue there.  The author confirmed that the update was never sent to PyPi therefore 'pip install' would be getting the version that still had the error in it.  pip install should get 0.16.1 now, which includes the fix.  Closing this ticket - feel free to re-open if fresh pip upgrade doesn't solve the problem.  Thanks for pointing it out.

**Closed by caver456** 2017-11-23 19:43 UTC
Labels: bug, help wanted, Priority:Medium
