### ISSUE TITLE
RadioLog not communicating with Sartopo

### ISSUE THREAD

**Issue by johnpictin** [ncssar/radiolog#437] opened 2020-08-05 17:30 UTC
When RadioLog and Sartopo are running on seperate systems, Sartopo is not receiving the appropriate commands to setup new markers corresponding to the new teams. It does work when they are hosted on the same machine. The radiolog config file was set with the appropriate address for the Sartopo server and using wireshark we could see that the Sartopo server received a get statement, but the Sartopo instance failed to respond.

**Comment by caver456** [comment] 2020-08-05 17:37
We're having the same trouble here - not sure why, or when it started.  It's not entirely clear if this is a sartopo issue or a radiolog issue.  A few debug notes that have been helpful:

- using postman on the sender is an easier/quicker way to do the testing at this level, versus the 'complete' method of using fsTester and a virtual serial port bridge
- changing the debug level between 1 and 9 shows all the goop that radiolog receives

So - on sar.jar 4159, sending the following get request from postman, taken from our radiolog log file, does work i.e. results in an updated locator on the map, as long as a locator group was created with Fleet 100:
http://localhost:8080/rest/location/update/position?lat=39.36870333333333&lng=-120.60149666666666&id=FLEET:100-1204

This is strange, because the same request didn't work in our command trailer.  So the debug will probably be upping the debug level in the trailer and seeing what happens.

John, if you read this far, could you send the text of the get request from the radiolog log file?

**Comment by caver456** [comment] 2020-08-05 17:46
'changing the debug level between 1 and 9' refers to the java command in SARTopoOffline.bat: change the --debug=<1-9> switch at the end of that line; 9 is crazy, 1 doesn't show the requests, so it's a matter of finding out the least-verbose level number that still shows the incoming requests on a successful locator update.  I'll have to find that out here at home where I do actually have working locators.  Will post the magic number here later today or tomorrow.

**Comment by johnpictiin** [comment] 2020-08-05 18:26
I will get some files for you.

John

**Comment by caver456** [comment] 2020-08-05 20:06
Here's what I get in debug=9 when the locator comes in and it does show correctly (4159):
```
...
...
[Winstone 2020/08/05 13:02:08] - Thread entering wait state
[Winstone 2020/08/05 13:02:08] - Waiting for a URI line
[Winstone 2020/08/05 13:02:08] - URI Line: GET /rest/location/update/position?lat=39.31870333333333&lng=-120.60149666666666&id=FLEET:100-1204 HTTP/1.1
[Winstone 2020/08/05 13:02:08] - Header: User-Agent: PostmanRuntime/7.24.1
[Winstone 2020/08/05 13:02:08] - Header: Accept: */*
[Winstone 2020/08/05 13:02:08] - Header: Cache-Control: no-cache
[Winstone 2020/08/05 13:02:08] - Header: Postman-Token: 20f67eff-b60f-4fd6-8693-ae42174cc32c
[Winstone 2020/08/05 13:02:08] - Header: Host: localhost:8080
[Winstone 2020/08/05 13:02:08] - Header: Accept-Encoding: gzip, deflate, br
[Winstone 2020/08/05 13:02:08] - Header: Connection: keep-alive
[Winstone 2020/08/05 13:02:08] - Header: Cookie: JSESSIONID=d69f73400a6a3158ee64a2db1ff2d0d4
[Winstone 2020/08/05 13:02:08] - Found cookie: [Cookie: name=JSESSIONID value=d69f73400a6a3158ee64a2db1ff2d0d4 version=0 path=null domain=null comment=null maxAge=-1 secure=false] 
[Winstone 2020/08/05 13:02:08] - Found session cookie: d69f73400a6a3158ee64a2db1ff2d0d4 
[Winstone 2020/08/05 13:02:08] - Starting request on host:[default] with id: 1596657728649
[Winstone 2020/08/05 13:02:08] - URL Match - path: /rest/location/update/position
[Winstone 2020/08/05 13:02:08] - No cached filter chain available. Calculating for cacheKey=REQUEST:URI:/rest/location/update/position
[Winstone 2020/08/05 13:02:08] - Processing with RD: spring
[Winstone 2020/08/05 13:02:08] - FORWARD: servlet=spring, path=/rest/location/update/position
[Winstone 2020/08/05 13:02:08] - Resetting buffer - discarding 0 bytes
[Winstone 2020/08/05 13:02:08] - Executing Filter: sqliteDBFilter
[Winstone 2020/08/05 13:02:08] - Executing Filter: requestPropertyFilter
[Winstone 2020/08/05 13:02:08] - Setting the request encoding from (null) to UTF-8
[Winstone 2020/08/05 13:02:08] - Setting response character encoding to UTF-8
[Winstone 2020/08/05 13:02:08] - Parsing parameters: lat=39.31870333333333&lng=-120.60149666666666&id=FLEET:100-1204 (using encoding UTF-8)
[Winstone 2020/08/05 13:02:08] - Param line: {lng=-120.60149666666666, id=FLEET:100-1204, lat=39.31870333333333}
[Winstone 2020/08/05 13:02:08] - Called ServletResponse.getOutputStream()
[Winstone 2020/08/05 13:02:08] - Headers prepared for writing: [Server: Winstone Servlet Engine v0.9.10, Content-Type: text/plain;charset=UTF-8, Cache-Control: no-cache, Content-Length: 2, Connection: Keep-Alive, Date: Wed, 05 Aug 2020 20:02:08 GMT, X-Powered-By: Servlet/2.5 (Winstone/0.9.10)]
[Winstone 2020/08/05 13:02:08] - Committing response body
[Winstone 2020/08/05 13:02:08] - Response: HTTP/1.1 200 OK
[Winstone 2020/08/05 13:02:08] - Header: Server: Winstone Servlet Engine v0.9.10
[Winstone 2020/08/05 13:02:08] - Header: Content-Type: text/plain;charset=UTF-8
[Winstone 2020/08/05 13:02:08] - Header: Cache-Control: no-cache
[Winstone 2020/08/05 13:02:08] - Header: Content-Length: 2
[Winstone 2020/08/05 13:02:08] - Header: Connection: Keep-Alive
[Winstone 2020/08/05 13:02:08] - Header: Date: Wed, 05 Aug 2020 20:02:08 GMT
[Winstone 2020/08/05 13:02:08] - Header: X-Powered-By: Servlet/2.5 (Winstone/0.9.10)
[Winstone 2020/08/05 13:02:08] - Written 2 bytes to response body
[Winstone 2020/08/05 13:02:08] - ServletOutputStream flushed
[Winstone 2020/08/05 13:02:08] - Written 2 bytes to response body
[Winstone 2020/08/05 13:02:08] - ServletOutputStream flushed
[Winstone 2020/08/05 13:02:08] - Written 2 bytes to response body
[Winstone 2020/08/05 13:02:08] - Finishing request id:  1596657728649
[Winstone 2020/08/05 13:02:08] - ReqPool: Request released - available: 9
[Winstone 2020/08/05 13:02:08] - RspPool: Response released - available: 9
[Winstone 2020/08/05 13:02:08] - Processed complete request: headerParseTime=2ms totalTime=6ms path=/rest/location/update/position?lat=39.31870333333333&lng=-120.60149666666666&id=FLEET:100-1204
[Winstone 2020/08/05 13:02:08] - Allocating request/response: RequestHandlerThread[#3]
[Winstone 2020/08/05 13:02:08] - ReqPool: Using pooled request - available: 8
[Winstone 2020/08/05 13:02:08] - RspPool: Using pooled response - available: 8
[Winstone 2020/08/05 13:02:08] - Parsing socket info
[Winstone 2020/08/05 13:02:08] - Waiting for a URI line
[Winstone 2020/08/05 13:02:09] - Webapp classloader found class locally when loading #0
...
...
```
However sometimes it doesn't work and I'm trying to figure out a pattern...

**Comment by caver456** [comment] 2020-08-05 20:12
By the way, I get identical java log output if a request is received but there is no locator object on the current map.  This makes sense because the request doesn't specify a map id - the locator shows up on all maps that have a listening locator object.

**Comment by RadiosPRN** [comment] 2021-01-02 00:19
Anything ever figured out about this? I'm having the same problem.

**Comment by caver456** [comment] 2021-01-02 00:43
Happy New Year - we still haven't seen locators in our trailer in several
months now.  The latest debug we did (in September and again in November)
was to revert to an earlier sar.jar.  Locators worked on 4151, but not on
4159 or 4160.  This was just a quick test so it's possible that some other
factor than sar.jar version was the culprit.  It sadly hasn't been a
priority for us to track down any further, with postman or fiddler or such.

**Comment by RadiosPRN** [comment] 2021-01-02 03:00
Ok thanks! Just wanted to make sure the issue wasn’t solved without being updated here.

**Comment by johnpictiin** [comment] 2021-01-03 01:14
Hello everyone,

I'm having the same trouble too and have been trying to troubleshoot it as
it would be really handy. I'm using sartopo offline (desktop) and the
strange part is that if I access an older map where the locator was working
I find the latest markers are in there, but not in the current map where I
want them. Maybe I need to delete the locator object in the old map, or
make sure that it has timed out. It could be that an old listener is
snagging the data before a new one gets it. Does SARTopo watch for the
mapname when it receives the post and could the mapname be appended to what
is sent from RadioLog so as to point the data to the right table in the
database?

Just some thoughts.

John

**Comment by caver456** [comment] 2021-01-03 01:28
Sartopo doesn't want the mapID to be part of the locator request.  Not sure
about all the inner workings (or not-workings) but apparently the locator
request itself is map-agnostic - it's the listener (the Locator Group
object) that pairs up the locator with the map.  Interesting question, if I
understood you correctly - is the locator being consumed by an old map and
can only be consumed once like a pop-tart, such that it's gone before the
map that wants it ever sees it?  These are questions for the sartopo help
folks, but I won't plan to submit a new ticket now, since I'd want to sit
down and review previous tickets first.

Here's the request that radiolog sends - radiolog.py line 1069:

self.getString = "http://" + self.sarsoftServerName +
":8080/rest/location/update/position?lat=" + str(lat) + "&lng=" + str(lon) +
"&id=FLEET:" + fleet + "-"

# if callsign = "Radio ..." then leave the getString ending with hyphen for
now, as a sign to defer
                            #  sending until accept of change callsign
dialog, or closeEvent of NewEntryWidget, whichever comes first;
                            #  otherwise, append the callsign now, as a
sign to send immediately
                            if not devTxt.startswith("Radio "):
                                self.getString = self.getString + devTxt

**Comment by caver456** [comment] 2021-01-03 01:54
adding some notes from Steve who tried this in Sept and again in Nov (cause both of us forgot that he tried in Sept...:<  )

--------------

email thread 8/11/2020:
I did try earlier versions on my computer, all versions worked though sometimes they would not work and I haven't figured out the pattern.  I like 4152 because it says what map IDs the locator is being forwarded to.  debug=9 shows all the goop.

PM steve <steve------> wrote:
Regarding locators, have you tried with an older sartopo release like 4151? 

--------------

email thread 9/11/2020:
Thanks that is good info.  I just today started getting a java crash error jn 4159 and 4160 and probably earlier versions when starting STO with locators.  Either Java or windows related since windows auto updated in the last few days.  Caltopo help folks are investigating.  Wonder if its related.  Will have to wait til next week to check further.

On Fri, Sep 11, 2020, 2:57 PM steve <steve------> wrote:

So you probably know all this., FWIW

I went to 91 to look for locators.  Changed sar.jar to 4151. Locators worked like a charm.  Watched for stuff using fiddler; did not see much that looked like it was related. Changed to 4159 and 4160. Neither showed locator received.  Never changed anything with radiolog for the entire session.  Went back to 4151 worked correctly.

Not much, but...

------------

from me to Steve 11/12/2020:

Last I remember is that we confirmed that radiolog is getting the radio coordinates and showing them in the new entry widget correctly, and the log says it's sending the http request correctly, but no sign of life after that: radiolog doesn't print the response and the sartopo log didn't indicate a thing.  So next steps would be trying to send it by hand from the dispatch computer using postman and looking for the response, and after that would probably be running fiddler on the server.

**Comment by johnpictiin** [comment] 2021-01-03 17:38
Thanks for the added info.

Much appreciated.

John

**Comment by RadiosPRN** [comment] 2021-01-04 20:41
I thought I would add some info after spending a bit of time tinkering today. I was running radiolog on 1 machine and sartopo offline (4210) with a locator object on another on the same LAN. I set the server in radiolog to the other machine's IP (unsure if that made a difference). On first time key up from a radio I would usually (not always) get this in radiolog:

[ ERROR ]   exception during sending of GET request: HTTPConnectionPool(host='192.168.50.4', port=8080): Max retries exceeded with url: /rest/location/update/position?lat=38.****4666666667&lng=-83.****8166666667&id=FLEET:104-Team%20Bravo (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000001BD3971FFA0>, 'Connection to 192.168.50.4 timed out. (connect timeout=0.0001)'))

After additional transmissions on the same radio I would usually get this:

[ ERROR ]   exception during sending of GET request: HTTPConnectionPool(host='192.168.50.4', port=8080): Read timed out. (read timeout=0.0001)

and a locator icon would populate on the map appropriately. If I read through some of the other issues correctly I believe radiolog is supposed to wait to send the location data to sartopo until after the radio name change dialog pops up and is entered so that the correct name for the radio is sent (only on first time key up). This was not happening because the error was happening immediately after transmission and not waiting until after the name change dialog box was closed. I don't know if that has anything to do with this or not but basically the locators are working for me from the second transmission and after on each individual radio. I'm not a programmer so once it gets into the code it rapidly goes over my head unless I have specific instructions but if there is something I need to check that would be of help let me know. I was also wondering what is supposed to be entered for the server when using sartopo online?

**Comment by caver456** [comment] 2021-01-09 16:11
thanks for the notes, that's a good assessment of what the code is doing.
We'll probably wait til we install the latest sar.jar to do more testing
here.  As far as working online, I don't think radiolog will currently send
requests over the internet.  There's some goop with signed requests that
has to happen.  We have a pip package that does that at
https://github.com/ncssar/sartopo_python but haven't integrated it into
radiolog and it's actually not clear that we'd need to.  Something to look
at in the future.

**Comment by caver456** [comment] 2021-02-10 20:19
So we installed the latest (4210) on all our computers in the command
trailer, and now locators seem to work.  We've only done one test and
haven't tried it in the field since the upgrade, but, can has anyone else
tried with 4210?

**Comment by johnpictiin** [comment] 2021-02-10 21:55
For those who are having trouble getting the locater object working in
SARTopo Desktop, make sure that the only locater object that is active (not
expired) is the one on the current map.

 If you have a map with a locater object that hasn't expired or is set to
never expire, this map continues to collect the location updates sent from
RadioLog. Even if no one has the map open, the data sent from RadioLog will
be posted to that map. If you create another map before the first locater
object has expired, a new locater object will not pick up the Fleetsync
data. Opening the earlier map and expiring the listener lets the locater
object on the newest map pick up the Fleetsync data. I haven't tried this
on the newest SARTopo build, but I will be doing that soon.

From what I recall, SARTopo documentation suggested that all maps with
active listeners would get the data, but that hasn't worked for me. It
posts to the first listener it finds in the database and stops

John P
Castlegar Search and Rescue

**Comment by caver456** [comment] 2021-02-10 22:08
huh, wonder if that could have been our issue all along.  I'll try a couple
of back-to-back maps with never-expire listeners and see if the most recent
one still works.  We've been in the habit of setting the listeners to
never-expire.  Thanks for the lead, I'll report back in the next few days.

**Comment by caver456** [comment] 2021-02-13 05:02
Thanks John, great description.  I was never really clear on all that.
After some testing tonight, I think that's exactly what has been happening
to us all along, and still DOES happen on 4210 (caltopo-desktop.exe):

I tested a new map with a new locator group tonight (on our trailer server
running 4210), and no locator showed up after incoming radio traffic.  So I
went to the earlier map from a few days ago where it did work, looked at
its locator group, changed its 'stop listening' attribute to 'now'.  We've
been in the habit - at my guidance, ironically - of setting 'stop
listening' to 'never'.  Sure enough the old map also had the locators from
tonight's radio traffic.  So, I went to several of our previous maps and
changed 'stop listening' to 'now', then confirmed the new locator group was
still listening.

Confirmed the whole test again by making one new map with a new locator
group, doing some traffic, watching the locator show up; making another new
map with a new locator group, doing some traffic, watching the absence of
locator, going back to the first new map, observed the most recent radio
traffic there.  Set 'stop listening' to 'now' on the first new map, did
some more radio traffic, and watched the new locator show up on the second
new map.  So it sure looks like the theory is all confirmed.

It's interesting that we probably do have some older maps with 'stop
listening' set to 'never', but the new listener is still working.  As if
there is actually some age limit in there, where 'never' actually means a
month or something.  Guess I'll look at the network traffic and see what
json is getting sent when you select 'never'.

Anyway, many thanks!

**Comment by johnpictiin** [comment] 2021-02-13 07:15
I'm glad to hear my suspicion was confirmed on your installation as well.
Since I started to make sure the locator was expired on past maps it's been
working consistently.

John

**Comment by caver456** [comment] 2021-02-13 15:04
the 'stop listening' setting determines the properties.expires value in the
outbound LocatorGroup request.  When set to 'Never', the json value is
null.  For any other setting, the json value is the actual timestamp in
milliseconds of when it should stop listening.  So maybe something in their
code is setting the upper limit on locator age.

It does seem like this is a bug report: the locator is getting gobbled up
by one (or more?) maps and is not going to the current map which ironically
is the only one where you actually want it.  It also seems like any time a
user adds a new locator group, there would be implicit intent to expire any
matching locator group (same callsign / fleet ID / email) immediately on
all other maps - that seems like a larger feature request so it probably
won't happen, but, is that basically the way you would want to use it too?

**Comment by johnpictiin** [comment] 2021-02-13 23:30
Actually, reflecting on this, there is a use for being able to have
multiple maps have access the locator data. For instance, a planning map vs
a status map. Planners would probably be interested in seeing a track of
where teams have been to quickly determine how much of an assignment was
completed and to know roughly where everyone had been. However, on a
seperate status map you might want the locators without a track, basically
to know where is everybody now.

Maybe it is something to ask SARTopo support. Is it a matter of having a
table that the listener puts all incoming locater updates in and then the
locater objects in the maps glean the data from there? That table would be
accessible to all maps, have to be limited to the latest x number of
updates so it would never overflow, there would be a chance for each map to
get the data before it disappeared. That way if a locater was left on the
worst that would happen is that their database would grow and some maps
would have data that didn't apply added to them but could be cleaned out
later.

I'm just thinking process, because I'm not a coder by trade. I don't know
how much sense that made or how the SARTopo database is configured.

John

**Comment by caver456** [comment] 2021-02-14 00:35
yeah I see what you mean about the need to have multiple maps see the same
locators.  Not sure what the 'best' way to do this would be.  It probably
is a sql table like you describe behind the scenes.  When I looked on maps
from months ago during the testing last night, they did actually have
locators from last night, because their listeners / locator groups were set
to never stop listening.

Anyway, the fact that it's a bug seems clear, so I'll go ahead and send
that in to caltopo, and I'll submit from the web interface so that it's
public rather than private.

**Comment by caver456** [comment] 2021-03-16 16:07
Just an update: we had two more opportunities to use locators over the
weekend.  Everything was working, so, this lends more weight to your theory
that too-many-unexpired-listeners was the problem.

Separately, we had issues with multiple locators of the same callsign
showing up; I think this was due to some LAN interruptions that we had,
but, I'll try and make sure radiolog can deal with network interruptions
gracefully, without making a duplicate locator object.  If anyone else has
seen similar stuff, please let me know.

**Comment by caver456** [comment] 2021-03-22 18:14
Closing this issue just to clean things up.  Thanks all for helping out with the mystery.

To sum up, it sounds like the problem was that we had 'too many' unexpired listeners on old maps.  Expiring those listeners, and making it a practice to set 'stop listening' to '1 day' going forward, seems to be the answer.

If anyone finds a reason to think otherwise, we should definitely reopen this issue.

**Closed by caver456** 2021-03-22 18:14 UTC
Labels: Priority:High, bug, interop
