### ISSUE TITLE
Quick message buttons and status options disabled on new entry form

### ISSUE THREAD

**Issue by SAR85** [ncssar/radiolog#455] opened 2021-09-14 02:10 UTC
When creating a new entry, the message shortcut buttons and team status options are disabled and cannot be selected. Keyboard shortcuts for the message also do not work. Buttons and status options are enabled when amending a message.

**Comment by caver456** [comment] 2021-09-14 02:22
Thanks for the detail.  Due to some turnover early this year in volunteer coding personnel, the whole radiolog project main branch is basically broken.  It's fairly high on the priority list to fix it, but, basically for now I'd suggest grabbing a much older version, I'd suggest https://github.com/ncssar/radiolog/tree/644341110c2150e005c7bc1cea9d0be4de59a2cd - that suggestion has worked for some other folks too.  Let me know if that does the trick, but, let's leave this issue open so that it does get addressed at some point.

**Comment by SAR85** [comment] 2021-09-18 03:47
Thanks for the suggestion, I'll check it out.

**Comment by RadiosPRN** [comment] 2022-06-29 01:08
This is no longer an issue since rolling back the main branch. Probably could be closed.

**Comment by caver456** [comment] 2022-06-29 03:12
Good finds on these three issues.  Will think a bit on whether there's a
point to leaving them open and adding a label to indicate they are specific
to the master-cb branch.  Thoughts on that?

**Comment by caver456** [comment] 2022-07-02 12:43
Fixed on master by reverting last month, as @RadiosPRN points out.   The issue remains on the master-cj branch which we hope to glean the good stuff from at some point in the future.

**Comment by caver456** [comment] 2022-07-19 03:06
closing as duplicate of #448

**Closed by caver456** 2022-07-19 03:06 UTC
Labels: master-cj
